// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core_dart/firebase_core_dart.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfAmc7UrtdEWFb3DI3G1xsT-9Y_Tk_NaI',
    appId: '1:476145737402:web:1fcc2a48ebf75fd8b5ac83',
    messagingSenderId: '476145737402',
    projectId: 'skinior-e9cd7',
    authDomain: 'skinior-e9cd7.firebaseapp.com',
    storageBucket: 'skinior-e9cd7.appspot.com',
    measurementId: 'G-MNV063FYHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmhaI3Iv0nD2V4taHrqKl7hkf0pcLMvHw',
    appId: '1:476145737402:android:5789e26fcc129f2ab5ac83',
    messagingSenderId: '476145737402',
    projectId: 'skinior-e9cd7',
    storageBucket: 'skinior-e9cd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf0TcrnHF5Ar8qzjQSYAwzaAbRwd5DmKc',
    appId: '1:476145737402:ios:f1708b616229a691b5ac83',
    messagingSenderId: '476145737402',
    projectId: 'skinior-e9cd7',
    storageBucket: 'skinior-e9cd7.appspot.com',
    iosBundleId: 'com.example.skinior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf0TcrnHF5Ar8qzjQSYAwzaAbRwd5DmKc',
    appId: '1:476145737402:ios:29c054d795bbb207b5ac83',
    messagingSenderId: '476145737402',
    projectId: 'skinior-e9cd7',
    storageBucket: 'skinior-e9cd7.appspot.com',
    iosBundleId: 'com.example.skinior.RunnerTests',
  );
}
