# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  # Use dynamic frameworks by default to resolve Firebase modular headers issues
  use_frameworks! :linkage => :dynamic
end

target 'skiniorf' do
  config = use_native_modules!

  # Firebase pods - using dynamic frameworks for proper Swift header generation
  pod 'FirebaseCore'
  pod 'FirebaseCoreExtension'
  pod 'FirebaseAuth'
  pod 'FirebaseAuthInterop'
  pod 'FirebaseAppCheckInterop'
  pod 'GoogleUtilities'
  pod 'FirebaseFirestoreInternal'
  pod 'RecaptchaInterop'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Enable Hermes debugger for Bridgeless mode
    # This fixes the HeadersTimeoutError when trying to connect debugger
    installer.pods_project.targets.each do |target|
      if target.name == 'React-RuntimeApple'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HERMES_ENABLE_DEBUGGER=1'
        end
      end
    end
  end
end
